In [45]:
import pandas as pd
import numpy as np

# Load the data

In [46]:
df_preproc = pd.read_csv('../absenteeism/data/Preprocessed_absenteeism_data.csv')

In [47]:
df_preproc.head()

reason 1  reason 2  reason 3  reason 4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month  Day of the week  
0         2     1                          4      7                1  
1         1     0                          0      7                1  
2         0     0                          2      7                2  
3         2     0                          4      7                3  
4         2     1                          2      7                3

# Target definition

In [48]:
df_preproc['Absenteeism Time in Hours'].median()

3.0

In [49]:
df_preproc['Absenteeism'] = np.where(df_preproc['Absenteeism Time in Hours'] > df_preproc['Absenteeism Time in Hours'].median(), 1, 0)

In [50]:
df_preproc['Absenteeism'].sum()/df_preproc.shape[0]

0.45571428571428574

In [51]:
df_preproc.drop(columns ='Absenteeism Time in Hours', inplace = True )

# Feature and target selection

In [53]:
df_preproc.shape

(700, 15)

In [68]:
X = df_preproc.drop(columns='Absenteeism')

In [69]:
y = df_preproc['Absenteeism']

# Standardize numerical features

In [70]:
X.columns

Index(['reason 1', 'reason 2', 'reason 3', 'reason 4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Month', 'Day of the week'],
      dtype='object')

In [71]:
X_unscaled = X[['Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Month', 'Day of the week']]

In [72]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_unscaled)

StandardScaler()

In [73]:
X_scaled = scaler.transform(X_unscaled)

In [60]:
X_scaled

array([[ 1.00584437,  0.41281584, -0.53606239, ...,  0.26848661,
         0.18272635, -0.68370352],
       [-1.57468098, -1.1418824 ,  2.13080317, ..., -0.58968976,
         0.18272635, -0.68370352],
       [-0.6541427 ,  1.42674947,  0.24830984, ..., -0.58968976,
         0.18272635, -0.00772546],
       ...,
       [ 1.62456682, -0.93909568, -1.32043461, ..., -0.58968976,
        -0.3882935 ,  0.66825259],
       [ 0.19094163, -0.93909568, -0.69293683, ..., -0.58968976,
        -0.3882935 ,  0.66825259],
       [ 1.03602595,  0.07483796,  0.56205873, ...,  0.26848661,
        -0.3882935 ,  0.66825259]])

In [74]:
X.drop(columns = ['Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Month', 'Day of the week'], inplace = True)

In [78]:
X[['Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Month', 'Day of the week']] = X_scaled
X

reason 1  reason 2  reason 3  reason 4  Transportation Expense  \
0           0         0         0         1                1.005844   
1           0         0         0         0               -1.574681   
2           0         0         0         1               -0.654143   
3           1         0         0         0                0.854936   
4           0         0         0         1                1.005844   
..        ...       ...       ...       ...                     ...   
695         1         0         0         0               -0.654143   
696         1         0         0         0                0.040034   
697         1         0         0         0                1.624567   
698         0         0         0         1                0.190942   
699         0         0         0         1                1.036026   

     Distance to Work       Age  Daily Work Load Average  Body Mass Index  \
0            0.412816 -0.536062                -0.806331         0.767431   
1           -1.141882  2.130803                -0.806331         1.002633   
2            1.426749  0.248310                -0.806331         1.002633   
3           -1.682647  0.405184                -0.806331        -0.643782   
4            0.412816 -0.536062                -0.806331         0.767431   
..                ...       ...                      ...              ...   
695         -0.533522  0.562059                -0.853789        -1.114186   
696         -0.263140 -1.320435                -0.853789        -0.643782   
697         -0.939096 -1.320435                -0.853789        -0.408580   
698         -0.939096 -0.692937                -0.853789        -0.408580   
699          0.074838  0.562059                -0.853789        -0.408580   

     Education  Children      Pets     Month  Day of the week  
0    -0.447980  0.880469  0.268487  0.182726        -0.683704  
1    -0.447980 -0.019280 -0.589690  0.182726        -0.683704  
2    -0.447980 -0.919030 -0.589690  0.182726        -0.007725  
3    -0.447980  0.880469 -0.589690  0.182726         0.668253  
4    -0.447980  0.880469  0.268487  0.182726         0.668253  
..         ...       ...       ...       ...              ...  
695   2.232242  0.880469 -0.589690 -0.388293        -0.007725  
696  -0.447980 -0.019280  1.126663 -0.388293        -0.007725  
697   2.232242 -0.919030 -0.589690 -0.388293         0.668253  
698   2.232242 -0.919030 -0.589690 -0.388293         0.668253  
699  -0.447980 -0.019280  0.268487 -0.388293         0.668253  

[700 rows x 14 columns]

# Train test split

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.8)

# Logistic regression

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

## Training the model

In [18]:
logreg = LogisticRegression()

In [19]:
logreg.fit(X_train,y_train)

LogisticRegression()

In [20]:
logreg.score(X_train, y_train)

0.7892857142857143

## Analyze coefficients

In [21]:
logreg.intercept_

array([-0.24550561])

In [22]:
logreg.coef_

array([[ 1.92807051,  0.24226126,  1.67612132,  1.04876969,  0.66400024,
        -0.08164757, -0.21455906, -0.15326456,  0.17597914, -0.07305284,
         0.42081146, -0.49584396,  0.16437864, -0.10568985]])

In [23]:
feature_names = X_unscaled.columns.values

In [27]:
summary_table = pd.DataFrame (columns = ['Feature name'], data = feature_names)
summary_table['Coefficient'] = np.transpose(logreg.coef_)

In [28]:
summary_table

Feature name  Coefficient
0                  reason 1     1.928071
1                  reason 2     0.242261
2                  reason 3     1.676121
3                  reason 4     1.048770
4    Transportation Expense     0.664000
5          Distance to Work    -0.081648
6                       Age    -0.214559
7   Daily Work Load Average    -0.153265
8           Body Mass Index     0.175979
9                 Education    -0.073053
10                 Children     0.420811
11                     Pets    -0.495844
12                    Month     0.164379
13          Day of the week    -0.105690

In [29]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', logreg.intercept_[0]]

In [32]:
summary_table.sort_index(inplace = True)
summary_table

Feature name  Coefficient
0                 Intercept    -0.245506
1                  reason 1     1.928071
2                  reason 2     0.242261
3                  reason 3     1.676121
4                  reason 4     1.048770
5    Transportation Expense     0.664000
6          Distance to Work    -0.081648
7                       Age    -0.214559
8   Daily Work Load Average    -0.153265
9           Body Mass Index     0.175979
10                Education    -0.073053
11                 Children     0.420811
12                     Pets    -0.495844
13                    Month     0.164379
14          Day of the week    -0.105690